apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: helheim-triggerbinding
  namespace: {{ .Values.global.namespace }}
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)