apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    pods: "10"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"