apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-helheim-trigger-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: staging
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: helheim-app-
        labels:
          tekton.dev/pipeline: helheim-cicd
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: helheim-cicd
        params:
          - name: github-repo-url
            value: '$(tt.params.gitrepositoryurl)'
          - name: github-repo-revision
            value: '$(tt.params.gitrevision)'
