---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Chart.Name }}-admin-{{ .Chart.Version }}"
  namespace: "{{ .Values.global.namespace }}"
  labels:
    app: "{{ .Chart.Name }}"
    version: "{{ .Chart.Version }}"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.global.serviceAccountNames.importer}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Chart.Name }}-admin-{{ .Chart.Version }}"
